// This file is auto-generated by Supabase CLI
// Run: npm run db:generate-types to update

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      players: {
        Row: {
          id: string
          name: string
          nickname: string | null
          color: string
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          nickname?: string | null
          color: string
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          nickname?: string | null
          color?: string
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      games: {
        Row: {
          id: string
          game_type: 'dominoes' | 'rummy' | 'mahjong'
          completion_type: 'rounds' | 'points'
          max_rounds: number | null
          max_points: number | null
          status: 'active' | 'completed' | 'cancelled'
          winner_id: string | null
          started_at: string
          ended_at: string | null
        }
        Insert: {
          id?: string
          game_type: 'dominoes' | 'rummy' | 'mahjong'
          completion_type: 'rounds' | 'points'
          max_rounds?: number | null
          max_points?: number | null
          status?: 'active' | 'completed' | 'cancelled'
          winner_id?: string | null
          started_at?: string
          ended_at?: string | null
        }
        Update: {
          id?: string
          game_type?: 'dominoes' | 'rummy' | 'mahjong'
          completion_type?: 'rounds' | 'points'
          max_rounds?: number | null
          max_points?: number | null
          status?: 'active' | 'completed' | 'cancelled'
          winner_id?: string | null
          started_at?: string
          ended_at?: string | null
        }
      }
      game_players: {
        Row: {
          id: string
          game_id: string
          player_id: string
          final_score: number
        }
        Insert: {
          id?: string
          game_id: string
          player_id: string
          final_score?: number
        }
        Update: {
          id?: string
          game_id?: string
          player_id?: string
          final_score?: number
        }
      }
      scores: {
        Row: {
          id: string
          game_id: string
          player_id: string
          round: number
          score: number
          created_at: string
        }
        Insert: {
          id?: string
          game_id: string
          player_id: string
          round: number
          score: number
          created_at?: string
        }
        Update: {
          id?: string
          game_id?: string
          player_id?: string
          round?: number
          score?: number
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
